const homeRoutes=require("./home.route")
const categoryMiddleware=require("../../middlewares/client/category.middleware")
const cartMiddleware=require("../../middlewares/client/cart.middleware")
const productRoutes=require("./product.route")
const cartRoutes=require("./cart.routes")
const checkoutRoutes=require("./checkout.routes")
const searchRoutes=require("./search.route")
const userRoutes=require("./user.route")
const userMiddleware=require("../../middlewares/client/user.middleware")
const settingMiddleware=require("../../middlewares/client/setting.middleware")
module.exports=(app)=>{
  app.use(categoryMiddleware.category)
  app.use(cartMiddleware.cartId)
  app.use(userMiddleware.infoUser)
  app.use(settingMiddleware.settingGeneral)

  app.use("/",homeRoutes)
  app.use("/products",productRoutes)
  app.use("/cart",cartRoutes)
  app.use("/checkout",checkoutRoutes)
  app.use("/search",searchRoutes)
  app.use("/user",userRoutes)
}
